# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(310, 211)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(160, 150, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.setBtn = QtWidgets.QPushButton(Dialog)
        self.setBtn.setGeometry(QtCore.QRect(70, 150, 75, 23))
        self.setBtn.setObjectName("setBtn")
        self.label_hd = QtWidgets.QLabel(Dialog)
        self.label_hd.setGeometry(QtCore.QRect(20, 40, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_hd.setFont(font)
        self.label_hd.setAutoFillBackground(False)
        self.label_hd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hd.setObjectName("label_hd")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(102, 90, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setInputMask("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label_stat = QtWidgets.QLabel(Dialog)
        self.label_stat.setGeometry(QtCore.QRect(10, 10, 291, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_stat.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_stat.setFont(font)
        self.label_stat.setToolTipDuration(2)
        self.label_stat.setAutoFillBackground(True)
        self.label_stat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stat.setObjectName("label_stat")
        self.label_bl = QtWidgets.QLabel(Dialog)
        self.label_bl.setGeometry(QtCore.QRect(10, 90, 81, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_bl.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_bl.setFont(font)
        self.label_bl.setObjectName("label_bl")
        self.radioButtons = QtWidgets.QRadioButton(Dialog)
        self.radioButtons.setGeometry(QtCore.QRect(230, 80, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtons.setFont(font)
        self.radioButtons.setChecked(True)
        self.radioButtons.setObjectName("radioButtons")
        self.radioButtonm = QtWidgets.QRadioButton(Dialog)
        self.radioButtonm.setGeometry(QtCore.QRect(230, 100, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonm.setFont(font)
        self.radioButtonm.setObjectName("radioButtonm")
        self.label_unit = QtWidgets.QLabel(Dialog)
        self.label_unit.setGeometry(QtCore.QRect(190, 92, 35, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_unit.setFont(font)
        self.label_unit.setObjectName("label_unit")
        self.buttonBox.raise_()
        self.label_hd.raise_()
        self.lineEdit.raise_()
        self.label_stat.raise_()
        self.setBtn.raise_()
        self.label_bl.raise_()
        self.radioButtons.raise_()
        self.radioButtonm.raise_()
        self.label_unit.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Timer app"))
        self.setBtn.setText(_translate("Dialog", "SET"))
        self.label_hd.setText(_translate("Dialog", "Set Timer"))
        self.lineEdit.setText(_translate("Dialog", "1"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Enter time"))
        self.label_stat.setToolTip(_translate("Dialog", "Shows current status of the program"))
        self.label_stat.setText(_translate("Dialog", "Not Set"))
        self.label_bl.setText(_translate("Dialog", "Time set to :"))
        self.radioButtons.setText(_translate("Dialog", "Seconds"))
        self.radioButtonm.setText(_translate("Dialog", "Minutes"))
        self.label_unit.setText(_translate("Dialog", "s"))

