# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(330, 280)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/ic.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 310, 151))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.label_unit = QtWidgets.QLabel(self.tab_1)
        self.label_unit.setGeometry(QtCore.QRect(190, 50, 35, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_unit.setFont(font)
        self.label_unit.setObjectName("label_unit")
        self.radioButtonm = QtWidgets.QRadioButton(self.tab_1)
        self.radioButtonm.setGeometry(QtCore.QRect(230, 58, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonm.setFont(font)
        self.radioButtonm.setObjectName("radioButtonm")
        self.radioButtons = QtWidgets.QRadioButton(self.tab_1)
        self.radioButtons.setGeometry(QtCore.QRect(230, 38, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtons.setFont(font)
        self.radioButtons.setChecked(True)
        self.radioButtons.setObjectName("radioButtons")
        self.label_hd = QtWidgets.QLabel(self.tab_1)
        self.label_hd.setGeometry(QtCore.QRect(10, 8, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_hd.setFont(font)
        self.label_hd.setAutoFillBackground(False)
        self.label_hd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hd.setObjectName("label_hd")
        self.setBtn = QtWidgets.QPushButton(self.tab_1)
        self.setBtn.setGeometry(QtCore.QRect(70, 90, 75, 23))
        self.setBtn.setObjectName("setBtn")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.tab_1)
        self.buttonBox.setGeometry(QtCore.QRect(160, 90, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit.setGeometry(QtCore.QRect(100, 48, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setInputMask("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label_bl = QtWidgets.QLabel(self.tab_1)
        self.label_bl.setGeometry(QtCore.QRect(10, 48, 81, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_bl.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_bl.setFont(font)
        self.label_bl.setObjectName("label_bl")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_pm_work = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_pm_work.setGeometry(QtCore.QRect(30, 27, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_pm_work.setFont(font)
        self.lineEdit_pm_work.setInputMask("")
        self.lineEdit_pm_work.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_pm_work.setClearButtonEnabled(False)
        self.lineEdit_pm_work.setObjectName("lineEdit_pm_work")
        self.label_unit_4 = QtWidgets.QLabel(self.tab_2)
        self.label_unit_4.setGeometry(QtCore.QRect(90, 30, 45, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_unit_4.setFont(font)
        self.label_unit_4.setObjectName("label_unit_4")
        self.label_unit_5 = QtWidgets.QLabel(self.tab_2)
        self.label_unit_5.setGeometry(QtCore.QRect(250, 30, 45, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_unit_5.setFont(font)
        self.label_unit_5.setObjectName("label_unit_5")
        self.lineEdit_pm_break = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_pm_break.setGeometry(QtCore.QRect(190, 29, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_pm_break.setFont(font)
        self.lineEdit_pm_break.setInputMask("")
        self.lineEdit_pm_break.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_pm_break.setClearButtonEnabled(False)
        self.lineEdit_pm_break.setObjectName("lineEdit_pm_break")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 10, 75, 13))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(189, 10, 75, 13))
        self.label_16.setObjectName("label_16")
        self.pushButton_pm_break = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_pm_break.setEnabled(True)
        self.pushButton_pm_break.setGeometry(QtCore.QRect(120, 65, 80, 23))
        self.pushButton_pm_break.setObjectName("pushButton_pm_break")
        self.pushButton_pm_work = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_pm_work.setGeometry(QtCore.QRect(30, 65, 75, 23))
        self.pushButton_pm_work.setObjectName("pushButton_pm_work")
        self.pushButton_pm_reset = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_pm_reset.setGeometry(QtCore.QRect(120, 95, 75, 23))
        self.pushButton_pm_reset.setObjectName("pushButton_pm_reset")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox_mm_2 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_mm_2.setGeometry(QtCore.QRect(30, 50, 90, 17))
        self.checkBox_mm_2.setObjectName("checkBox_mm_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.label_stat = QtWidgets.QLabel(Dialog)
        self.label_stat.setEnabled(True)
        self.label_stat.setGeometry(QtCore.QRect(10, 10, 310, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_stat.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_stat.setFont(font)
        self.label_stat.setToolTipDuration(2)
        self.label_stat.setAutoFillBackground(True)
        self.label_stat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stat.setObjectName("label_stat")
        self.label_table_title = QtWidgets.QLabel(Dialog)
        self.label_table_title.setGeometry(QtCore.QRect(10, 195, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_table_title.setFont(font)
        self.label_table_title.setObjectName("label_table_title")
        self.label_dur = QtWidgets.QLabel(Dialog)
        self.label_dur.setEnabled(True)
        self.label_dur.setGeometry(QtCore.QRect(20, 240, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_dur.setFont(font)
        self.label_dur.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dur.setObjectName("label_dur")
        self.label_apm = QtWidgets.QLabel(Dialog)
        self.label_apm.setEnabled(True)
        self.label_apm.setGeometry(QtCore.QRect(70, 240, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_apm.setFont(font)
        self.label_apm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_apm.setObjectName("label_apm")
        self.label_kb = QtWidgets.QLabel(Dialog)
        self.label_kb.setEnabled(True)
        self.label_kb.setGeometry(QtCore.QRect(220, 240, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_kb.setFont(font)
        self.label_kb.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kb.setObjectName("label_kb")
        self.label_table = QtWidgets.QLabel(Dialog)
        self.label_table.setEnabled(True)
        self.label_table.setGeometry(QtCore.QRect(15, 220, 300, 42))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_table.setPalette(palette)
        self.label_table.setAutoFillBackground(True)
        self.label_table.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_table.setObjectName("label_table")
        self.label_ms = QtWidgets.QLabel(Dialog)
        self.label_ms.setEnabled(True)
        self.label_ms.setGeometry(QtCore.QRect(140, 240, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ms.setFont(font)
        self.label_ms.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ms.setObjectName("label_ms")
        self.label_table.raise_()
        self.tabWidget.raise_()
        self.label_stat.raise_()
        self.label_table_title.raise_()
        self.label_dur.raise_()
        self.label_apm.raise_()
        self.label_kb.raise_()
        self.label_ms.raise_()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Productivity app"))
        self.label_unit.setText(_translate("Dialog", "s"))
        self.radioButtonm.setText(_translate("Dialog", "Minutes"))
        self.radioButtons.setText(_translate("Dialog", "Seconds"))
        self.label_hd.setText(_translate("Dialog", "Set Timer"))
        self.setBtn.setText(_translate("Dialog", "SET"))
        self.lineEdit.setText(_translate("Dialog", "1"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Enter time"))
        self.label_bl.setText(_translate("Dialog", "Time set to :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dialog", "Timer Mode"))
        self.lineEdit_pm_work.setText(_translate("Dialog", "2"))
        self.lineEdit_pm_work.setPlaceholderText(_translate("Dialog", "Enter time"))
        self.label_unit_4.setText(_translate("Dialog", "minutes"))
        self.label_unit_5.setText(_translate("Dialog", "minutes"))
        self.lineEdit_pm_break.setText(_translate("Dialog", "1"))
        self.lineEdit_pm_break.setPlaceholderText(_translate("Dialog", "Enter time"))
        self.label_15.setText(_translate("Dialog", "Work Duration"))
        self.label_16.setText(_translate("Dialog", "Break Duration"))
        self.pushButton_pm_break.setText(_translate("Dialog", "Take a Break"))
        self.pushButton_pm_work.setText(_translate("Dialog", "Start session"))
        self.pushButton_pm_reset.setText(_translate("Dialog", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Pomodoro"))
        self.checkBox_mm_2.setText(_translate("Dialog", "Manual Monitor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Manual Mode"))
        self.label_stat.setToolTip(_translate("Dialog", "Shows current status of the program"))
        self.label_stat.setText(_translate("Dialog", "Not Set"))
        self.label_table_title.setText(_translate("Dialog", "Last session\'s stats-"))
        self.label_dur.setText(_translate("Dialog", "None"))
        self.label_apm.setText(_translate("Dialog", "0"))
        self.label_kb.setText(_translate("Dialog", "0"))
        self.label_table.setText(_translate("Dialog", " Duration  |     APM    |   Mouse events  | Keyboard events"))
        self.label_ms.setText(_translate("Dialog", "0"))

import ic_rc
